### ISSUE TITLE
Test fails when a module depending on uses import path that matches 'paths' config

### ISSUE THREAD

**Issue by sakai-y** [ryohey/tsconfig-paths-jest#1]
Thank you for this nice module.

I found a problem.

tsconfig.json
```json
  "paths": {
    "model/*": [ "src/model" ]
  }
```

a code in `node_modules`
```js
var foo = require('../model/foo');
```

In this case, Jest fails.
```
Configuration error:

Could not locate module ../model/foo mapped as:
/path/to/project/src/model/foo.

Please check your configuration for these entries:
{
  "moduleNameMapper": {
    "/model\/(.*)/": "/path/to/project/src/model/$1"
  },
  "resolver": null
}
```

**Comment by sakai-y** [comment]
I've fixed locally. But could not push for permission.
Please give me permission to push or take a change below.
```diff
-      k.replace(/\*/, "(.*)"),
+      `^{k.replace(/\*/, "(.*)")}`,
```

**Comment by JakeGinnivan** [comment]
I worked around this issue with this:

```
var tsConfigMappedPaths = require('tsconfig-paths-jest')(tsconfig)

for (const key of Object.keys(tsConfigMappedPaths)) {
    tsConfigMappedPaths[`^${key}`] = tsConfigMappedPaths[key]
    delete tsConfigMappedPaths[key]
}
```

**Comment by sakai-y** [comment]
I found [this](https://kulshekhar.github.io/ts-jest/user/config/#paths-mapping)...

**Comment by ryohey** [comment]
@sakai-y Thank you for letting me know. I guess we should use `pathsToModuleNameMapper` rather than this module.

**Comment by JakeGinnivan** [comment]
Yeah, ts-jest added a helper for this in v23, I'm still on v22 for another issue

**Comment by sakai-y** [comment]
@JakeGinnivan Thanks for the information. I'm glad that I could help you out.
